# Generated by Django 4.1.2 on 2022-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('uname', models.CharField(default='', max_length=20)),
                ('emails', models.EmailField(default='', max_length=20)),
                ('ano', models.IntegerField(default='', max_length=20)),
                ('pwd', models.CharField(default='', max_length=20)),
                ('cpwd', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
